- name: setting up Nginx
  hosts: web
  become: yes
  tasks:
  - name: Installing Nginix
    ansible.builtin.package:
      name: nginx
      state: present

  - name: Stating Nginx and enabling
    ansible.builtin.service:
      name: nginx
      state: started

  - name: Stating Nginx and enabling  
    ansible.builtin.service:
      name: nginx
      state: enabled


