- name: setting up Nginx
  hosts: web
  become: yes
  tasks:
  - name: Installing Nginix
    ansible.builtin.package:
      name: nginx
      status: present

  - name: Stating Nginx and enabling
    ansible.builtin.service:
      name: nginx
      status: started

  - name: Stating Nginx and enabling  
    ansible.builtin.service:
      name: nginx
      status: enabled


